-- 코드를 입력하세요
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES from REST_INFO r
WHERE FAVORITES = (
SELECT FAVORITES from REST_INFO
WHERE FOOD_TYPE = r.FOOD_TYPE
ORDER BY FAVORITES DESC
limit 1)
GROUP BY FOOD_TYPE
ORDER BY FOOD_TYPE DESC;