-- 코드를 입력하세요
SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d')
FROM REST_REVIEW r
JOIN MEMBER_PROFILE m
ON r.MEMBER_ID = m.MEMBER_ID
WHERE r.MEMBER_ID = (
    SELECT MEMBER_ID from REST_REVIEW 
    GROUP BY MEMBER_ID
    ORDER BY count(REVIEW_ID) DESC limit 1
) 
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC;