-- 코드를 입력하세요
SELECT DISTINCT USER_ID, PRODUCT_ID from ONLINE_SALE o
WHERE (
    SELECT COUNT(*) from ONLINE_SALE 
    WHERE USER_ID = o.USER_ID and PRODUCT_ID = o.PRODUCT_ID
) > 1
ORDER BY USER_ID ASC, PRODUCT_ID DESC;