-- 코드를 입력하세요
(SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') as s, PRODUCT_ID, USER_ID, SALES_AMOUNT 
from ONLINE_SALE
WHERE DATE_FORMAT(SALES_DATE, "%Y-%m") = '2022-03')
UNION
(SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') as s, PRODUCT_ID, NULL, SALES_AMOUNT from OFFLINE_SALE
WHERE DATE_FORMAT(SALES_DATE, "%Y-%m") = '2022-03')
ORDER BY s ASC, PRODUCT_ID ASC, USER_ID ASC;