-- 코드를 입력하세요
SELECT h.FLAVOR from FIRST_HALF h
JOIN (
    SELECT FLAVOR, sum(TOTAL_ORDER) as TOTAL from JULY
    GROUP BY FLAVOR
) as j
ON h.FLAVOR = j.FLAVOR
GROUP BY h.FLAVOR
ORDER BY sum(TOTAL_ORDER + TOTAL) DESC
limit 3;